databases:
  - name: anaacoss-db
    plan: free

services:
  - type: web
    name: anaacoss
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn anaacoss.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: anaacoss.settings.prod
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "anaacoss.in,www.anaacoss.in,anaacoss.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://anaacoss.in,https://www.anaacoss.in,https://anaacoss.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: anaacoss-db
          property: connectionString
