# Generated by Django 5.2.9 on 2026-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='placement',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('before', 'Before'), ('after', 'After')], default='gallery', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
