# Generated by Django 5.2.9 on 2026-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gender', 'category'], name='catalog_pro_gender_96e318_idx'),
        ),
    ]
