# Generated by Django 5.2.9 on 2026-04-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_gender_product_catalog_pro_gender_96e318_idx'),
        ('commerce', '0002_order_payment_status_order_selected_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='commerce.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='commerce.orderitem'),
        ),
        migrations.AddField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, upload_to='reviews/videos/'),
        ),
    ]
